### ISSUE TITLE
Scrollable post list?

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/josephdykstra.com#15]
```css
#post-list-div-or-whatever {
  height: calc(100vh - 360px); /* cant actually hardcode this because it is dynamic */
  overflow-y: scroll;
  overflow-x: hidden;
}
```
