### ISSUE TITLE
Increase text legibility

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/josephdykstra.com#61]
https://backchannel.com/how-the-web-became-unreadable-a781ddc711b6#.vpf66mvs6

Probably increase the font size.

Related #49, #60

**Comment by ArtskydJ** [comment]
Perhaps the colors can be:
```css
body {
    background-color: #fcfcfc;
    color: #222222;
}
```
http://webaim.org/resources/contrastchecker/?fcolor=222222&bcolor=fcfcfc
